baseURL = "https://blog.igaryhe.io/"
languageCode = "zh-CN"
theme = "kiss"
hasCJKLanguage = true
author = "Dan"
title = "ない"
pageinate = 5
enableRobotsTXT = true

[params.rss]
includeContent = true
authorName = "Dan"
authorEmail = "igaryhe@gmail.com"

[params.social]
twitter = "igaryhe1"
github = "igaryhe"
email = "igaryhe@gmail.com"
about = "about"
rss = "index.xml"

[params.social.config]
platforms = ["twitter", "github", "email", "about", "rss"]

[params.info]
homeTitle = "ない"
author = "Dan"
poweredby = true

[taxonomies]
tag ="tags"

[params.assets]
customCSS = ["css/custom.css"]
